### ISSUE TITLE
improving the REPL

### ISSUE THREAD

**Issue by dandougherty** [salmans/Razor#75]
First let me make sure that I'm doing this right -- opening an issue, that is (haven't done it before).
Does this have the right visibility, can someone reply?

What I am about here is getting some of the changes to the REPL done that we have already talked about.     Hope not too much work.

**Comment by dandougherty** [comment]
In subsequent posts I am going to record some improvements I'd like to see to the REPL.
First, though, here is an outright bug.

P & (Q | R)  throws a parsing error at the " | "

**Comment by dandougherty** [comment]
The treatment of "Truth" and "Falsehood" is a little buggy

Just writing 
Falsehood;
in the theory behaves fine (no models of course)

But if you have the sentence 
Truth;
in the theory the model-finding crashes.  

other cases:
 Truth & Falsehood ;  // no models, ok
  Truth | Falsehood;    // crash

**Comment by ryandanas** [comment]
As far as I can tell, everything has been addressed other than the theory parsing needing some serious reworking. That's best left in issue #57 .
