### ISSUE TITLE
couldn't build

### ISSUE THREAD

**Issue by dandougherty** [salmans/Razor#77]
Make failed for me, in the res branch.
At  first I got complaints about "text" 
> cabal: cannot configure attoparsec-0.13.0.2. It requires text >=1.1.1.3

I edited razor.cabal to say build-depends: ... text >=0.11 (instead of ==0.11)

but then I got 

> cannot configure mtl-2.1.3.1. It requires transformers ==0.3.*

and couldn't see how to edit the .cabal to address this.
Since I was just flailing around anyway, not knowing what I was doing,  I threw up my hands.

I did NOT push changes.

Dan

**Comment by pseudometric** [comment]
You need to `git pull`; you’re looking at commit `dcc27d82` or earlier.

**Comment by pseudometric** [comment]
…also, make sure you’re actually on the right branch (`git pull; git checkout res`); it’s odd that you’d be looking at a version of the file with that version bound in it. It was never the tip of a branch, so you’d have to check it out specifically to see it. You’d see it if you were still on the `razor` branch, though.

**Comment by pseudometric** [comment]
(Issued solved via email by checking out the right version of the code and updating to the latest Haskell Platform.)
